### ISSUE TITLE
ValueError: Invalid isoformat string: '2022-11-11T14:45:54.90086Z'

### ISSUE THREAD

**Issue by doritogon303** [treeben77/rblx-open-cloud#2]
Ignoring exception in slash command 'h':
Traceback (most recent call last):
  File "C:\Users\doritogon\AppData\Local\Programs\Python\Python310\lib\site-packages\rblxopencloud\datastore.py", line 157, in set
    return EntryVersion(data["version"], data["deleted"], data["contentLength"], data["createdTime"], data["objectCreatedTime"], self, key, self.scope if self.scope else scope)
  File "C:\Users\doritogon\AppData\Local\Programs\Python\Python310\lib\site-packages\rblxopencloud\datastore.py", line 23, in __init__
    self.key_created = datetime.datetime.fromisoformat(key_created[0:26])
ValueError: Invalid isoformat string: '2022-11-11T14:45:54.90086Z'

**Comment by TreeBen77** [comment]
Hey Doritogon303! could you show some code of what you're doing, making sure you don't leak your api key or any other keys?

**Comment by TreeBen77** [comment]
Thanks for the traceback, I've found the problem and think I have fixed it. I believe you haven't reproduced this bug multiple times  but you should no longer see this error in the library after you update, which can be easily done with the shell command:
```
pip install rblx-open-cloud --upgrade
```

I won't close this issue yet in case you'd like to reply and thanks for using my library!
